<a href="https://colab.research.google.com/github/VolitiveGoblin/IT-262-Assignments/blob/main/CP_PERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

simulationDF=pd.read_csv("/content/drive/MyDrive/Collab/simulatinDataset.csv")
simulationDF.head(2)

,A,B,C,D,E,F,G,H,I,J,EOP
0,6.045858,5.178993,5.016073,2.298449,5.520913,2.919441,7.483400,1.788597,6.251385,2.596106,NaN
1,5.081443,4.396005,3.897385,2.744611,4.564977,1.698484,3.421265,2.958545,12.844984,2.190488,NaN

In [12]:
paths=['ADEJ','BCDEJ', 'BCFGJ', 'BCFHJ', 'BI']
pathsDF=pd.DataFrame(columns=paths)
ADEJ=[]
BCDEJ=[]
BCFGJ=[]
BCFHJ=[]
BI=[]
for index, row in simulationDF.iterrows():
  ADEJ.append(row['A']+row['D']+row['E']+row['J'])
  BCDEJ.append(row['B']+row['C']+row['D']+row['E']+row['J'])
  BCFGJ.append(row['B']+row['C']+row['F']+row['G']+row['J'])
  BCFHJ.append(row['B']+row['C']+row['F']+row['H']+row['J'])
  BI.append(row['B']+row['I'])

pathsDF['ADEJ']=ADEJ
pathsDF['BCDEJ']=BCDEJ
pathsDF['BCFGJ']=BCFGJ
pathsDF['BCFHJ']=BCFHJ
pathsDF['BI']=BI

pathsDF.head(2)
pathsDF['critical']=pathsDF.idxmax(axis=1)
print(pathsDF.critical.value_counts())

BCDEJ    33820
BCFGJ    25474
BI       21925
BCFHJ    14756
ADEJ      4025
Name: critical, dtype: int64